name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    # run CD ONLY if CI succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- LOGIN TO GHCR ----------
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # deploy using your script
      - name: Deploy Container
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh
      
      - name: Show container logs
        run: docker logs --tail 100 cats-dogs-mlops-api-1

      - name: Inspect running container
        run: |
          docker exec cats-dogs-mlops-api-1 ls -R

      - name: Wait for API startup
        run: |
          echo "Waiting for API..."
          for i in {1..30}; do
            if curl -s http://localhost:8000/health; then
              echo "API is ready!"
              exit 0
            fi
            echo "Still waiting..."
            sleep 2
          done
          echo "API failed to start"
          exit 1

      - name: Install dependencies
        run: pip install requests

      - name: Run Smoke Test
        run: python scripts/smoke_test.py

      - name: Run Monitoring Feedback Collection
        run: python scripts/collect_feedback.py
