name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    # run CD ONLY if CI succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # deploy using your script
      - name: Deploy Container
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh

      - name: Wait for container startup
        run: sleep 15

      - name: Install dependencies
        run: pip install requests

      - name: Run Smoke Test
        run: python scripts/smoke_test.py

      - name: Run Monitoring Feedback Collection
        run: python scripts/collect_feedback.py
